### ISSUE TITLE
swr_convert attempted to read or write protected memory

### ISSUE THREAD

**Issue by DenisIvanovIvanov** [Ruslan-B/FFmpeg.AutoGen.Questions#10]
I've a camera and I'm trying to stream both video and audio to the file. The video is always H.264 encoded and the plan for the audio is to use AAC. I'm following https://ffmpeg.org/doxygen/4.0/transcode_aac_8c-example.html

Since AAC requires 1024 samples, frames have to be buffered. I will skip the decoder part because it works just fine

Here I'm adding the frame to the buffer
    
          public void AddFifoSample(AVFrame* inputFrame)
          {
                var samples = InitConvertedSamples(inputFrame->nb_samples);
               ConvertSamples(inputFrame->extended_data, samples, inputFrame->nb_samples);

            if (ffmpeg.av_audio_fifo_realloc(_audioFifo, ffmpeg.av_audio_fifo_size(_audioFifo) + inputFrame->nb_samples) < 0)
            {
                // throw
                string asd = string.Empty;
            }

            if (ffmpeg.av_audio_fifo_write(_audioFifo, (void**)samples, inputFrame->nb_samples) < 0)
            {
                // throw;
                string asd = string.Empty;
            }
        }

Because I didn't find how to convert this to C#
            if (!(*converted_input_samples = calloc(output_codec_context->channels,
                 sizeof(**converted_input_samples)))) {
                fprintf(stderr, "Could not allocate converted input sample pointers\n");
                return AVERROR(ENOMEM);
            }`
 
I'm using `stackalloc` to allocate the number of pointers needed

          private byte* InitConvertedSamples(int frameSize)
          {
            byte* samples = stackalloc byte[_outputAudioCtx->channels];

            if(ffmpeg.av_samples_alloc(&samples, null, _outputAudioCtx->channels, frameSize, _outputAudioCtx->sample_fmt, 0) < 0)
            {
                ffmpeg.av_freep(samples);
                ffmpeg.av_free(samples);
                throw new FfmpegEngineException(CaptureEngineErrorType.Internal, "Unable to allocate samples.");
            }

            return samples;
        }`

This works ( I suppose ). After that I'm converting it

        private void ConvertSamples(byte** frameData, byte* inputSamples, int frameSize)
        {
            if (ffmpeg.swr_convert(_resamplerCtx, &inputSamples, frameSize, frameData, frameSize) < 0)
            {
                // throw
            }
        }`

But I'm getting `Attempted to read or write protected memory`. Why is that?
This is how I create the `swr_context`

             _resamplerCtx = ffmpeg.swr_alloc_set_opts(null,
                ffmpeg.av_get_default_channel_layout(_outputAudioCtx->channels),
                _outputAudioCtx->sample_fmt,
                _outputAudioCtx->sample_rate,
                ffmpeg.av_get_default_channel_layout(_inputAudioCtx->channels),
                _inputAudioCtx->sample_fmt,
                _inputAudioCtx->sample_rate, 0, null);

            if (ffmpeg.swr_init(_resamplerCtx) < 0)
            {
                throw new FfmpegEngineException(CaptureEngineErrorType.FailedToOpen, "Could not allocate resampler context");
            }`

**Comment by Ruslan-B** [comment]
Well just take a look into ```swr_convert``` declaration: 
```
   /// <summary>Convert audio.</summary>
        /// <param name="s">allocated Swr context, with parameters set</param>
        /// <param name="out">output buffers, only the first one need be set in case of packed audio</param>
        /// <param name="out_count">amount of space available for output in samples per channel</param>
        /// <param name="in">input buffers, only the first one need to be set in case of packed audio</param>
        /// <param name="in_count">number of input samples available in one channel</param>
        /// <returns>number of samples output per channel, negative value on error</returns>
        public static int swr_convert(SwrContext* @s, byte** @out, int @out_count, byte** @in, int @in_count)
```
Second parameter is *array of pointers*, in your case it is just input data which is most probably already misuse of the ffmpeg api.

```

**Comment by DenisIvanovIvanov** [comment]
Actually no, the problem was because I was allocating memory which then ffmpeg tries allocate again. 

        byte* samples = null;

        if (ffmpeg.av_samples_alloc(&samples, null, _outputAudioCtx->channels, frameSize, _outputAudioCtx->sample_fmt, 0) < 0)

Setting samples to null is enough.

**Comment by Ruslan-B** [comment]
So I can conclude it supposed to be a pointer to a pointer to byte array (no allocation needed indeed), just in case if you need access such structure.
