### ISSUE TITLE
FFmpeg dll x86

### ISSUE THREAD

**Issue by tqk2811** [Ruslan-B/FFmpeg.AutoGen.Questions#14]
I try to find but can't found x86 version on internet, is there it never existed?  
I need FFmpeg.AutoGen run in x86 version, but i don't know about c++ build.  

Is ffmpeg support x86? If true, can you build it please?  
Thankyou

**Comment by Ruslan-B** [comment]
any search engine tell you how to build FFmpeg for any platform and flavor - there are ton of guides how to do so.

**Comment by tqk2811** [comment]
Sorry, i found it. And forgot close this
