### ISSUE TITLE
Where is the download of the relevant DLL library resources?

### ISSUE THREAD

**Issue by 527395632** [Ruslan-B/FFmpeg.AutoGen.Questions#16]
Thread ERROR Message：Unable to load DLL 'swscale.5': The specified module could not be found.

![image](https://user-images.githubusercontent.com/20411721/110093171-5a371f00-7dd5-11eb-83b1-d23b38da7880.png)

**Comment by Ruslan-B** [comment]
P.S. check you log may be this is the problem [libx264 @ 000001afa93e9440] width not divisible by 2 (871x531)

**Comment by 527395632** [comment]
Yes, thank you very much for your support. At the same time, I'm very sorry for your photos. In the future, I will specially look at the ffmpeg use documents
