### ISSUE TITLE
Push bitmap to rtsp or rtmp server

### ISSUE THREAD

**Issue by ChengYen-Tang** [Ruslan-B/FFmpeg.AutoGen.Questions#18]
Hi @Ruslan-B ,
Can autogen push bitmap to rtsp or rtmp server? 

Thank.
Kenneth

**Comment by Ruslan-B** [comment]
I can give the only advice - look for examples in plain c. Your issue right now main repo with a lot of people watching it - however, if no one knows what are you asking - I cannot do much as well. :)
