### ISSUE TITLE
Recreate ffmpeg.autogen from custom built ffmpeg.dll

### ISSUE THREAD

**Issue by swhitaker1** [Ruslan-B/FFmpeg.AutoGen.Questions#19]
I generated cs files from custom built ffmpeg dlls.   The generated files have unrecognized c++ types and comparisons. Did you have to manually edit the generated .cs file and make corrections for things like "unsigned int" before you built FFmpeg.Autogen or did I miss a step?

**Comment by Ruslan-B** [comment]
No it is fully automatic, no manual changes are needed. Clang frontend normally parse such a thing as a primitive types, in your case I only can guess why it didn't happen. You most probably need to debug generation and I think do some extra handling in ```TypeHelper.GetTypeName```.
However, if construction you facing is part of standard header files I can take a look.

**Comment by swhitaker1** [comment]
I had to modify FFmpeg.functions.inline.g.cs

**Comment by Ruslan-B** [comment]
Yep inline the only exclusion as these functions part of C preprocessor, normally you have to do it once.
