### ISSUE TITLE
Does AutoGen support scale_npp?

### ISSUE THREAD

**Issue by ChengYen-Tang** [Ruslan-B/FFmpeg.AutoGen.Questions#27]
I found that using sws_scale to convert NV12 to RGB has a performance bottleneck. It seems that to solve this problem, we must use scale_npp to convert NV12 to YUV in the GPU, and then use sws_scale to convert YUV to RGB.

**Comment by Ruslan-B** [comment]
Vague questions = no answers.  Not in FFmpeg API not in this project.

**Comment by ChengYen-Tang** [comment]
But ffmpeg.exe can use scale_npp.

**Comment by Ruslan-B** [comment]
You can look into source code of ffmpeg.exe then or into FFmpeg documentation. As I see in the official API header files - there is no publicly exposed scale_npp function.
