### ISSUE TITLE
Example project outputs corrupted frames under Linux but not Windows

### ISSUE THREAD

**Issue by Arctis-Fireblight** [Ruslan-B/FFmpeg.AutoGen.Questions#28]
**Note: for support questions, please use [stackoverflow](https://stackoverflow.com/search?tab=newest&q=ffmpeg%20autogen) or special repository on [github.com](in special repository [github.com](https://github.com/Ruslan-B/FFmpeg.AutoGen.Questions/issues))**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
  - [ X ] bug report
  - [ ] feature request
  - [ ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

Running the example project on my Linux environment seems to corrupt the frames when decoding the mp4.
This behavior does not seem to occur on my Windows PC. 
(Problematic as my app will be Linux only.)
Here is an example: [https://www.dropbox.com/s/yffet0hiy4h7ngd/frame.00000307.jpg?dl=0](https://www.dropbox.com/s/yffet0hiy4h7ngd/frame.00000307.jpg?dl=0)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem*:

Run the example project under Ubuntu 20.04

* **What is the expected behavior?**

To see frames identical to the video file linked in the project.

* **Please tell us about your environment:**

Running Kubuntu 20.04 using .Net 5.0.
Tried with FFmpeg 4.2.4 and 4.4.1.

- version: 3.4

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by hglee** [comment]
Would you try AVPixelFormat.AV_PIX_FMT_BGRA (VideoFrameConverter
destination) and PixelFormat.Format32bppArgb (Bitmap) in DecodeAllFramesToImages ?

I also got bad image with 24 bpp but 32 bpp works.

**Comment by Arctis-Fireblight** [comment]
Why did I not think to try 32bpp... Yeah this works around the issue, and the tutorial project works flawlessly with this change! It is a bit strange to me that adding an alpha channel fixes the problem, but this gets me moving again. 

Thank you!!!
