### ISSUE TITLE
Parameter is not valid

### ISSUE THREAD

**Issue by rebelmx4** [Ruslan-B/FFmpeg.AutoGen.Questions#32]
When i use "FFmpeg.AutoGen.Example", a expection() is throwed.

how i send the video to you??
![image](https://user-images.githubusercontent.com/7813353/177074409-dd08247b-42ad-4fbd-b301-a773a7298beb.png)

**Comment by Ruslan-B** [comment]
I don't troubleshoot this kind of issues.
