### ISSUE TITLE
Field not found: 'FFmpeg.AutoGen.AVstream.codec'.

### ISSUE THREAD

**Issue by StrikingPopcorn** [Ruslan-B/FFmpeg.AutoGen.Questions#34]
Hello,

I am working on a program, that uses the ffme media element which has FFmpeg.AutoGen as a dependency and whenever I try to open an audio file I just get the error "Field not found: 'FFmpeg.AutoGen.AVstram.codec'.". So far I've spent a week on nothing else but troubleshooting my code and after figuring out that the problem already exists as soon as the program starts, I started to suspect the NuGet packages I use to cause issues. My worries first got proven after a test program, that had just the media element and FFmpeg.AutoGen installed worked until I installed another NuGet package and it's dependencies but after I had uninstalled all NuGet packages and reinstalled the media element and FFmpeg.AutoGen the error still persisted and a second test program that also just had these two NuGet packages installed, simply didn't work at all. All of the programs failed with the same error and I am completely out of ideas what else to try, so I come here in a search for help.

Sincerely
StrikingPopcorn

**Comment by Ruslan-B** [comment]
I see the only way you can get something like this you upgraded FFmpeg.AutoGen package to the latest version and ffme media element still uses the older package.  Ask this question in ffme media.
