### ISSUE TITLE
Specified method is not supported

### ISSUE THREAD

**Issue by nicolastmaia** [Ruslan-B/FFmpeg.AutoGen.Questions#39]
Hi. I'm trying to write a C# program that receives a audio stream in G.711u and I want to convert it to G.722.  

I found this lib but so far hasn't been able to use it because it keeps throwing this error whenever I run the program:
`Specified method is not supported`

This happens with whatever line of ffmpeg... I run, but the first one on my code is  
`AVIOContext* avioContext = ffmpeg.avio_alloc_context(null, 0, 0, null, null, null, null);`.

I'm developing on Windows 11, and according to the README: native libraries are already bundled in the project. That means there's no need to download ffmpeg and reference it or to run FFmpeg.AutoGen.CppSharpUnsafeGenerator, right?

Thanks in advance for any help you can give.

**Comment by Ruslan-B** [comment]
I can bet you forgot  something like ```DynamicallyLoadedBindings.Initialize();``` before starting to work with ffmpeg - depends from implementation package you are using.
In any case you need to provide native ffmpeg binaries of your choose.

**Comment by nicolastmaia** [comment]
Nice. I didn't know I needed this initialize.
Is there some extra material you'd recommend I read in order to use this package?
Also, what do you mean by implementation package and where should I insert the ffmpeg binaries?

**Comment by Ruslan-B** [comment]
https://github.com/Ruslan-B/FFmpeg.AutoGen/tree/master/FFmpeg.AutoGen.Example

**Comment by nicolastmaia** [comment]
I'll take a look. Thanks!
