### ISSUE TITLE
DynamicallyLoadedBindings.LibrariesPath undefined & "Specified Method is not supported"

### ISSUE THREAD

**Issue by Ketone1** [Ruslan-B/FFmpeg.AutoGen.Questions#40]
Hi there, I don't know if this is a bug or if there is another way to go about this, however its still troubling me. I have looked around the internet for around a hour and cant find anything.

So the problem is on the FFmpeg.AutoGen.Example repository, it shows that I must define the root directory of the ffmpeg libraries. I am using the most recent version of FFmpeg.AutoGen aswell as the ffmpeg libraries. In the example it shows that to define the root directory of the libraries I must set "DynamicallyLoadedBindings.LibrariesPath" as the root directory path ([](https://github.com/Ruslan-B/FFmpeg.AutoGen/blob/master/FFmpeg.AutoGen.Example/FFmpegBinariesHelper.cs#L24C21-L24C60)). However, this is undefined. I also tried to set the directory with "ffmpeg.RootPath". However it still seemed to not be able to link the libraries since I get the access violation "Specified Method is not supported" when calling any type of function. So if you know how I can fix this, please tell me. Here's the code that I have:

case (int)CodecTypes.H264:
                    {
                        unsafe
                        {
                            var Path = Environment.CurrentDirectory;

                            ffmpeg.RootPath = Path;
                            DynamicallyLoadedBindings.Initialize();

                            AVCodecParserContext* parserContext = ffmpeg.av_parser_init((int)AVCodecID.AV_CODEC_ID_H264);
                            if (parserContext == null)
                            {
                                break;
                            }
                        }
                    }
                    break;

**Comment by Ruslan-B** [comment]
if you check out repo it works out the box till the moment you feed in something strange

**Comment by Ruslan-B** [comment]
all documentation is  provided - just read all from official website.

**Comment by Ruslan-B** [comment]
I don't know to put it right, depends from where you took binaries witch version - and flags to compile being used

**Comment by Ruslan-B** [comment]
just train uself on GPL version from repo

**Comment by Varmod** [comment]
I also ran into this, the issue is that you don't have the nuget `FFmpeg.AutoGen.Bindings.DynamicallyLoaded` installed, and most likely only have `FFmpeg.AutoGen`
