### ISSUE TITLE
Specified method is not supported  in CentOS

### ISSUE THREAD

**Issue by David-He** [Ruslan-B/FFmpeg.AutoGen.Questions#42]
I published the FFMpeg.Autogen.Example as linux-x64. and copy it in a CentOS  computer which has already compiled and installed ffmpeg in /usr/local/ffmpeg/lib. In the example code , I have set DynamicallyLoadedBindings.LibrariesPath = @"/usr/local/ffmpeg/lib".
But  the example just run to FFmpeg version info: 6.0.  Then get Specified method is not supported.
It seems can't find the ffmpeg lib.

But I published the same release in a UOS (like Debian) computer with same ffmpeg installed, it's running fine.

**Comment by Ruslan-B** [comment]
cent os known for hawing names for libraries in not well know and supported ways check binaries check loaders code - obviously, a different library which doesn't follow convention from Debian branch will not be loaded

**Comment by Ruslan-B** [comment]
like I much to to detect different distributives running linux, you have native loaders you ddlimport version where resolver can be coded

**Comment by David-He** [comment]
Thank you for your reply. I have already resolved it after reconfigure with --pkg-config-flags="--static" and make install ffmpeg.
