### ISSUE TITLE
How to encode from image to mp4 file use GPU?

### ISSUE THREAD

**Issue by xxtkidxx** [Ruslan-B/FFmpeg.AutoGen.Questions#43]
-

**Comment by Ruslan-B** [comment]
Well you have example project

**Comment by xxtkidxx** [comment]
> Well you have example project

Please give me link to sample. Thanks

**Comment by Ruslan-B** [comment]
You have one for encode in repo principles same -you have dive in details - obviously

**Comment by Ruslan-B** [comment]
It is complex stuff so level up you have all tools and how to use them it is not school from my side - please think as positive answer - As I need to work and spend time with my kids as well -all written on front page  there are tons information so filter it - open source in is to free - invest your time

**Comment by xxtkidxx** [comment]
> It is complex stuff so level up you have all tools and how to use them it is not school from my side - please think as positive answer - As I need to work and spend time with my kids as well -all written on front page there are tons information so filter it - open source in is to free - invest your time

I just asked your Project supports GPU encode , you said  "you have example project". After that, I ask you again, where is it?
I don't ask you to do it for me. Thank you for sharing.
On the other hand, I used a different approach for my work.

**Comment by Ruslan-B** [comment]
I never do baby siting expert for my kids, all is fine when you have 3 mln downloads and over 600 users or this repo besides I cannot estimate your skills as you history shows here on git hub - repo has and Example project and other links to study - I cannot see rationale in your thinking where you just ask blindly - so respect my time FFmpeg is can of worms - I just made you tool and open possibility - respect this all rules were being provided upfront you simply didn't read and happy ignored them
glad to hear you solved you problem - I don't have negative felling's at all

**Comment by xxtkidxx** [comment]
I greatly respect your project and your community contributions. If something I said make you unhappy, please forget and ignore it.

**Comment by Ruslan-B** [comment]
no offence made had to be assertive, hey, thank you
