### ISSUE TITLE
Will it work in mobile and web platform? 

### ISSUE THREAD

**Issue by Barshan-Mandal** [Ruslan-B/FFmpeg.AutoGen.Questions#45]
will it work in latest .net maui platforms and blazor web applications?If yes,show me some examples.

**Comment by Ruslan-B** [comment]
blazor, you kidding - works as mobile native - provided you can assemble ffmpeg binaries  - use case not clear

**Comment by Ruslan-B** [comment]
I'll keep i close but will reply if any other questions, besides- read at lest the front page,

**Comment by Barshan-Mandal** [comment]
here the use cases of mac linux and windows is described but not android ,ios,web.show me some examples in c# for .net maui and does it support ffprobe?

**Comment by Ruslan-B** [comment]
Have some dignity. Look over closed tickets. I have no examples but look here:

**Comment by Ruslan-B** [comment]
https://github.com/Ruslan-B/FFmpeg.AutoGen/issues/210
https://github.com/Ruslan-B/FFmpeg.AutoGen/issues/221

**Comment by Ruslan-B** [comment]
and the last one https://learn.microsoft.com/en-us/dotnet/standard/native-interop/native-library-loading

**Comment by Ruslan-B** [comment]
For IOS you have premade static import version and if you look in history of issues - it is being used successfully.

**Comment by Ruslan-B** [comment]
As for web well - we are not yet ready by now. Keep in mind it complex by power of 3 - I don't have time but always reply to normal questions. So mobile is possible but you have to put some effort - I do provide tools how you will use - cannot explain :).

**Comment by Ruslan-B** [comment]
IOS is here https://www.nuget.org/packages/FFmpeg.AutoGen.Bindings.StaticallyLinked

**Comment by Ruslan-B** [comment]
google it and https://github.com/quamotion/ffmpeg-win32/tree/master

**Comment by Barshan-Mandal** [comment]
i just need a  function in maui mobile platform that can take  arguments alike ffmpeg and execute it alike main ffmpeg .i want to use it as a service

**Comment by Barshan-Mandal** [comment]
> For IOS you have premade static import version and if you look in history of issues - it is being used successfully.

can you make it more easier

**Comment by Barshan-Mandal** [comment]
> google it and https://github.com/quamotion/ffmpeg-win32/tree/master

can i compile it for android and ios

**Comment by Ruslan-B** [comment]
yes, apparently you can - but this **_beyond this project scope_** - the binaries in repo needed only for generation.
**_you should look in different repositories or example on internet as this is none trivial process - platform and toolchain specific._**
afaik they are some people approached me  and I made what they advised and it appears to be working.
their work is private though.
