### ISSUE TITLE
Extracting frames from AVPackets over tcp stream?

### ISSUE THREAD

**Issue by ahmad-hl** [Ruslan-B/FFmpeg.AutoGen.Questions#9]
I'm trying to encode screenshots (on Client side), and decode them (on Server side) in realtime. However, **I couldn't initialize AVFormatContext properly**, so that I can **decode and retrieve the frames from the network stream**.

I send the encoded packets from client to server through NetworkStream. At the server, I receive byte[] payload which I pass to `retrieve_avPacket ` function as follows:

    //Retrieve AV packet from the received data
    public static unsafe AVPacket retrieve_avPacket(byte[] payload)
    {
        var avPacket = new AVPacket();
        ffmpeg.av_init_packet(&avPacket);

        fixed (byte* pData = payload)
        {
            avPacket.data = pData;
            avPacket.size = payload.Length;
        }

        return avPacket;
    }
I need to retrieve the frame from avPacket. Therefore, I changed `TryDecodeNextFrame `to be as follows:

  
     public bool TryDecodeNextFrame(AVPacket* _pPacket, out AVFrame frame)
    {
        ffmpeg.av_frame_unref(_pFrame);
        ffmpeg.av_frame_unref(_receivedFrame);
        int error;
        do
        {
            try
            {
              ffmpeg.avcodec_send_packet(_pCodecContext, _pPacket).ThrowExceptionIfError();
            }
            finally
            {
                ffmpeg.av_packet_unref(_pPacket);
            }

            error = ffmpeg.avcodec_receive_frame(_pCodecContext, _pFrame);
            if (error == ffmpeg.AVERROR_EOF)
            {
                frame = *_pFrame;
                return false;
            }

        } while (error == ffmpeg.AVERROR(ffmpeg.EAGAIN));
        error.ThrowExceptionIfError();
        frame = *_pFrame;

        return true;
    }

For some reason, I receive this exception **System.ApplicationException: 'End of file'**

I saved the first AVPacket to a file out.h264 to use it as url for `VideoStreamDecoder`. Afterward, I decode the AVPackets as I receive them from the network stream as follows:

    private static unsafe void DecodeStreamToImages(string url, AVPacket avPacket, NetworkStream stream)
    {
       using (var vsd = new VideoStreamDecoder(url, HWDevice))
        {
            var sourceSize = vsd.FrameSize;
            var sourcePixelFormat = vsd.PixelFormat;
            var destinationSize = sourceSize;
            var destinationPixelFormat = AVPixelFormat.AV_PIX_FMT_RGB24;
            byte[] payload ;
            AVPacket avPacket;

            using (var vfc = new VideoFrameConverter(sourceSize, sourcePixelFormat, destinationSize, destinationPixelFormat))
            {
                 var frameNumber = 0;
                byte[] payload;
                while (frameNumber < 200)
                {
                    while (vsd.TryDecodeNextFrame(&avPacket, out var frame))
                    {
                        var convertedFrame = vfc.Convert(frame);

                        using (var bitmap = new Bitmap(convertedFrame.width, convertedFrame.height, convertedFrame.linesize[0], PixelFormat.Format24bppRgb, (IntPtr)convertedFrame.data[0]))
                            bitmap.Save($"frame.{frameNumber:D8}.jpg", ImageFormat.Jpeg);

                        frameNumber++;
                    }
                    //Receive & Retrieve AV Packet
                    payload = ReceiveImageDataTCP(stream);
                    avPacket = retrieve_avPacket(payload);
                }
            }
        }
    }
In the main, the transmission and decoding logic is as follow:

        NetworkStream stream = client.GetStream();

        AVPacket avPacket;
        using (var fs = File.Open("out.h264", FileMode.Create))
        {
            byte[] payload= ReceiveImageDataTCP(stream);

            //Retrieve AV Packet and save as H264 encoded packet ==> out.h264
            avPacket = retrieve_avPacket(payload);
            using (var packetStream = new UnmanagedMemoryStream((&avPacket)->data, (&avPacket)->size)) packetStream.CopyTo(fs);
        }

        //decode frames to images, initavPack: packet read from file out.h264 
        DecodeStreamToImages("out.h264", initavPacket, stream);
**I'm trying to decode the AVPacket as I receive them from the network stream not from a url**. Specifically, the error is raised from `TryDecodeNextFrame ` function. For some reason, _pCodecContext still points to the url although I'm passing AVPacket explicitly without reading it from the input url.
**WHAT IS WRONG, AND HOW TO SOLVE IT?**

**Comment by Ruslan-B** [comment]
You have completely working example which is practically decodes file over HTTP - TCP is not that much of difference.
As just read data from the stream to buffer and then feed it to parser and then to decoder.
If you just google ```ffmpeg decode frame data from memory``` and follow one top first links from stackoverflow.com it will lead you eventually to:
https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/decode_video.c
So have to use ```av_parser_parse2``` https://ffmpeg.org/doxygen/4.0/group__lavc__parsing.html to form the packet.
On top of it to avoid exceptions you have to process correctly EAGAIN and AVERROR_EOF codes after you invoke ```avcodec_receive_frame```.

**Comment by Ruslan-B** [comment]
Closing issue
